"""Render measured Phase3 retrieval/model checkpoint and update handoff."""
from pathlib import Path
import json
from datetime import datetime,timezone
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
u=json.load(open('outputs/candidates/UNION-003/metrics.json'));m=json.load(open('outputs/experiments/GBDT-004/metrics.json'));best=next(r for r in m['models'] if r['model']==m['selected_model']);s=best['scores']['development_check'];f=u['final'];stamp=datetime.now(timezone.utc).isoformat()
lines=['# Phase 3 checkpoint','','All retrieval measurements use the same 1,000 balanced-country development S1 and all 10,320,219 training targets. Model check uses 505 development S1; calibration uses the other 495. Neither is final holdout or OOF model performance. Fold4 remains closed.','','## Retrieval union','','| Added route | Link recall | Complete entity recall | Oracle F0.5 | Avg candidates | P95 | P99 | New true links |','|---|---:|---:|---:|---:|---:|---:|---:|']
for r in u['incremental']:lines.append(f"| {r['added_route']} | {r['link_recall']:.2%} | {r['positive_entity_all_coverage']:.2%} | {r['oracle_macro_f0_5']:.5f} | {r['average_candidates_per_query']:.1f} | {r['candidate_quantiles']['p95']:.0f} | {r['candidate_quantiles']['p99']:.0f} | {r['new_true_links']} |")
lines+=['','The broad union prioritizes recall and is not yet a frozen production configuration. Expanded-token retrieval has poor marginal efficiency; targeted rescue/reranking should be tested. Per-route runtime, RSS and fit statistics: outputs/candidates/CHAR-001/metrics.json and TRANS-002/metrics.json. Complete/any recall excludes singletons; oracle credits perfect empty predictions and is not a matcher score.','','## First model tournament','','| Model | Calibration F0.5 | Check F0.5 | Precision | Recall | Singleton | Threshold |','|---|---:|---:|---:|---:|---:|---:|']
for path in ['outputs/experiments/GBDT-002/metrics.json','outputs/experiments/GBDT-004/metrics.json']:
 d=json.load(open(path))
 for r in d['models']:
  scores=r.get('scores');c=scores['development_check'];lines.append(f"| {r.get('name',r.get('model'))} | {scores['calibration']['macro_f0_5']:.5f} | {c['macro_f0_5']:.5f} | {c['micro_precision']:.2%} | {c['micro_recall']:.2%} | {c['singleton_f0_5']:.2%} | {r['threshold']:.2f} |")
lines+=['',f"Selected by calibration only: **{best['model']}**. India check F0.5 {best['scores']['India']['macro_f0_5']:.5f}; US {best['scores']['US']['macro_f0_5']:.5f}. Model uses name/address char3 candidates, not the full broad retrieval union.",'',f"Inner two-fold entity cross-fitting identified {m['hard_negatives']} training hard negatives; held-out target owners were excluded from each inner fit. Weighting those negatives 3× increased check precision but reduced macro F0.5 and singleton accuracy, so this branch was rejected. The independent transliteration feature branch improved calibration and check scores.",'','## Limits and next work','','Only 1,000 training S1 were used. The development check has been observed across experiments and architecture choices; do not present it as an untouched test set. No final test output or leaderboard submission exists. No GPU or EC2 launched. S3 stores 51 verified objects / 4,326,917,279 bytes; estimated storage run-rate $0.0927/month, actual billing unverified.','','Next: expand training/query coverage, persist efficient retrieval indexes, evaluate cross-country and collision-group robustness, fit OOF singleton/calibration decisions, inspect false merges, then determine whether dense rescue adds value on the remaining hard pairs. Do not immediately scale the broad ~900-candidate union to every test entity.']
Path('docs/PHASE3_CHECKPOINT.md').write_text('\n'.join(lines)+'\n')
fig,axes=plt.subplots(1,2,figsize=(13,5));rr=u['incremental'];axes[0].plot([r['average_candidates_per_query'] for r in rr],[100*r['link_recall'] for r in rr],marker='o');axes[0].set_xlabel('Average candidates / S1');axes[0].set_ylabel('True-link recall (%)');axes[0].set_title('Full-target union: recall versus volume');axes[0].grid(alpha=.2)
models=[]
for path in ['outputs/experiments/GBDT-002/metrics.json','outputs/experiments/GBDT-004/metrics.json']:
 for r in json.load(open(path))['models']:models.append((r.get('name',r.get('model')),r['scores']['development_check']['macro_f0_5']))
axes[1].barh([r[0] for r in models],[r[1] for r in models]);axes[1].set_xlim(0,1);axes[1].set_title('Small development-check matcher benchmark');axes[1].set_xlabel('Exact macro F0.5');fig.tight_layout();fig.savefig('docs/figures/phase3_checkpoint.png',dpi=150)
p=Path('STATUS.md');text=p.read_text();text+='\n## Latest Phase 3 checkpoint — '+stamp+'\n\n'+f"Broad candidate union link recall **{f['link_recall']:.2%}**, complete-entity recall **{f['positive_entity_all_coverage']:.2%}**, oracle macro **{f['oracle_macro_f0_5']:.5f}**, average candidates **{f['average_candidates_per_query']:.1f}**, P95 **{f['candidate_quantiles']['p95']:.0f}**, P99 **{f['candidate_quantiles']['p99']:.0f}**. Scope: 1,000 dev queries, full10.32M pool.\n\nBest calibration-selected matcher: GBDT-004 multiview, threshold {best['threshold']:.2f}; 505-entity check macro **{s['macro_f0_5']:.5f}**, precision **{s['micro_precision']:.2%}**, recall **{s['micro_recall']:.2%}**, singleton **{s['singleton_f0_5']:.2%}**. Not OOF/final holdout. First serious model exists; earlier no-model statements above describe the previous phase. Fold4 closed.\n\nS3 raw + processed complete, 51 checksum-verified objects, 4.33GB. Storage now accrues nominal cost (~$0.0927/month), actual bill unknown; compute $0. Expanded-token volume and nonASCII/hard-pair coverage remain concerns. See docs/PHASE3_CHECKPOINT.md for tables and next work.\n";text=text.replace('Learned-model training has not started.','Small learned matcher pilots are complete; full-scale training has not started.');p.write_text(text)
with Path('TIMELINE.md').open('a') as h:h.write(f'\n## {stamp} | Codex | Phase 3 measured checkpoint\n- Completed six full-target char3/4/5 routes, transliteration, expanded tokens, union ablations, two lexical GBDTs and multiview/hard-negative refinement.\n- Best calibration-selected pilot check macro {s["macro_f0_5"]:.6f}; broad union link recall {f["link_recall"]:.6f}. Not final holdout/OOF. Hard-negative weighting rejected on calibration.\n- S3 raw/processed SHA256 verified; 35 Parquet shards preserve all raw records. No rented compute.\n- Failures preserved: TRANS-001 temp-view connection scope, GBDT-001 reserved label alias, GBDT-003 reserved owner alias. Fresh runs succeeded.\n- Next: larger entity-split training, production retrieval throughput, singleton/OOF calibration and residual error rescue.\n')
print(json.dumps({'recall':f['link_recall'],'oracle':f['oracle_macro_f0_5'],'check_macro':s['macro_f0_5']}))
